date.timezone = America/Sao_Paulo
default_charset = "ISO-8859-1"
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL
log_errors = On
session.cookie_httponly = On
session.cookie_samesite = Strict
session.use_strict_mode = On
expose_php = Off
